# apiVersion: v1
# kind: Service
# metadata:
#   name: ingress-gitlab
#   #namespace: dev
# spec:
#   selector:
#     app: webservice
#   ports:
#     - protocol: TCP
#       port: 8888
#       targetPort: 8080
#   type: LoadBalancer


# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ing-gitlab
#   #namespace: kube-system
#   # annotations:
#   #   # app.kubernetes.io/instance: traefik-kube-system
#   #   # app.kubernetes.io/name: traefik
#   #   ingress.kubernetes.io/ssl-redirect: "false"
#   #   ingress.kubernetes.io/force-ssl-redirect: "false"
#   #   ingress.kubernetes.io/ssl-passthrough: "false"
# spec:
#   ingressClassName: traefik
#   rules:
#   - host: 
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: gitlab-webservice-default
#             port:
#               number: 8080