apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  #namespace: kube-system
  labels:
    app: app2  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: daniginga/iot-basic-backend:app2
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: app2-svc
  #namespace: kube-system  
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: app2

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2-ing
  #namespace: kube-system
  annotations:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
spec:
  rules:
  - host : app2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app2-svc
            port:
              number: 80
