
apiVersion: v1
kind: Service
metadata:
  name: argo-service
  #namespace: dev
spec:
  selector:
    app: argocd-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8080
  type: LoadBalancer