apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  namespace: dev

# Create a Role that allows managing resources in the new namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-application-controller
  namespace: dev
# rules:
# - apiGroups: ["*"]
#   resources: ["*"]
#   verbs: ["*"]

# Bind the Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-application-controller-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: dev
roleRef:
  kind: Role
  name: argocd-application-controller
  apiGroup: rbac.authorization.k8s.io
