apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  #namespace: kube-system
  labels:
    app: app1  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: ncameiri/iot-basic-backend:app1
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: app1-svc
  #namespace: kube-system  
spec:
  ports:
  - protocol: TCP
    port: 80
    #targetPort: 3000
    targetPort: 80
  selector:
    app: app1

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-ing
  #namespace: kube-system
  annotations:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
spec:
  rules:
  - host : app1.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1-svc
            port:
              number: 80
