# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "preparation.sh"

  # Kubernetes Master Server
  config.vm.define "dmarceliS" do |kmaster|
    kmaster.vm.box = "boxen/ubuntu-24.10"
    kmaster.vm.hostname = "dmarceliS"
    kmaster.vm.network "private_network", ip: "192.168.56.110"
    kmaster.vm.provider "virtualbox" do |v|
      v.name = "dmarceliS"
      v.memory = 2048
      v.cpus = 2
    end
  end

end
