# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "preparation.sh"

  # Kubernetes Master Server
  config.vm.define "dmarceliS" do |kmaster|
    kmaster.vm.box = "bento/ubuntu-18.04"
    kmaster.vm.hostname = "dmarceliS"
    kmaster.vm.network "private_network", ip: "192.168.56.110"
    kmaster.vm.provider "virtualbox" do |v|
      v.name = "kmaster"
      v.memory = 1024
      v.cpus = 1
    end
    kmaster.vm.provision "shell", path: "bootstrap_kmaster.sh"
  end

  config.vm.define "dmarceliSW" do |workernode|
    workernode.vm.box = "bento/ubuntu-18.04"
    workernode.vm.hostname = "dmarceliSW"
    workernode.vm.network "private_network", ip: "192.168.56.111"
    workernode.vm.provider "virtualbox" do |v|
      v.name = "dmarceliSW"
      v.memory = 1024
      v.cpus = 1
    end
    workernode.vm.provision "shell", path: "bootstrap_kworker.sh"
    end
  end
